# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_password — копия.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: #2C2C2C")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    color: #2CE429;\n"
"    font-size: 20pt;        /* размер текста */\n"
"    font-weight: regular;\n"
"    spacing: 10px;          /* расстояние между квадратиком и текстом */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 24px;            /* ширина квадратика */\n"
"    height: 24px;           /* высота квадратика */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: transparent;\n"
"    border-radius: 4px;     /* можно скруглить углы */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: #D9D9D9;\n"
"    border-radius: 4px;\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_10.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    color: #2CE429;\n"
"    font-size: 20pt;        /* размер текста */\n"
"    font-weight: regular;\n"
"    spacing: 10px;          /* расстояние между квадратиком и текстом */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 24px;            /* ширина квадратика */\n"
"    height: 24px;           /* высота квадратика */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: transparent;\n"
"    border-radius: 4px;     /* можно скруглить углы */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: #D9D9D9;\n"
"    border-radius: 4px;\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_10.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    color: #2CE429;\n"
"    font-size: 20pt;        /* размер текста */\n"
"    font-weight: regular;\n"
"    spacing: 10px;          /* расстояние между квадратиком и текстом */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 24px;            /* ширина квадратика */\n"
"    height: 24px;           /* высота квадратика */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: transparent;\n"
"    border-radius: 4px;     /* можно скруглить углы */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: #D9D9D9;\n"
"    border-radius: 4px;\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_10.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    color: #2CE429;\n"
"    font-size: 20pt;        /* размер текста */\n"
"    font-weight: regular;\n"
"    spacing: 10px;          /* расстояние между квадратиком и текстом */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 24px;            /* ширина квадратика */\n"
"    height: 24px;           /* высота квадратика */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: transparent;\n"
"    border-radius: 4px;     /* можно скруглить углы */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #D9D9D9;\n"
"    background: #D9D9D9;\n"
"    border-radius: 4px;\n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_10.addWidget(self.checkBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(30)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"background-color: #D9D9D9;\n"
"font-size: 30pt;\n"
"font-weight: regular;\n"
"color: #000000;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: #D9D9D9;\n"
"font-family: \"Alumni Sans\";\n"
"font-size: 15pt;\n"
"font-weight: regular;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("X:/Downloads/860787.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 12px;                 /* толщина дорожки (было 6px) */\n"
"    background: #D9D9D9;          /* цвет дорожки */\n"
"    border-radius: 6px;           /* скругление под новую толщину */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #2CE429;          /* цвет бегунка */\n"
"    border: 2px solid #999999;    /* рамка */\n"
"    width: 24px;                  /* ширина бегунка */\n"
"    height: 24px;                 /* высота бегунка (было 20px) */\n"
"    margin: -10px 0;              /* центрируем относительно дорожки */\n"
"    border-radius: 12px;          /* круг (половина от width/height) */\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #2CE429;\n"
"font-size: 25pt;\n"
"font-weight: regular;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setStyleSheet("border-radius: 15px;\n"
"background-color: #2CE429;\n"
"font-size: 30pt;\n"
"font-weight: regular;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #2CE429;\n"
"font-size: 35pt;\n"
"font-weight: regular;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 5)
        self.gridLayout.setRowStretch(2, 3)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_2.setText(_translate("MainWindow", "цифры"))
        self.checkBox.setText(_translate("MainWindow", "символы"))
        self.checkBox_4.setText(_translate("MainWindow", "нижний регистр"))
        self.checkBox_3.setText(_translate("MainWindow", "верхний регистр"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Колличество символов:</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать пароль"))
        self.label.setText(_translate("MainWindow", "Генератор паролей"))
